version: "3.0"
services:
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    container_name: puppy-db
    # volumes:
    #  - ./db:/var/lib/postgresql/data
 